# 参考:
# https://docs.rubocop.org/rubocop/cops.html
# https://docs.rubocop.org/rubocop-capybara/cops.html
# https://docs.rubocop.org/rubocop-performance/cops.html
# https://docs.rubocop.org/rubocop-rails/cops.html

require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
AllCops:
  Exclude:
    - db/schema.rb
    - bin/*
  NewCops: enable
Layout/LineLength:
  Max: 120
Lint/AmbiguousBlockAssociation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
  Enabled: true
Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true
Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test
Rails/EnvironmentVariableAccess:
  Enabled: false
Style/ArrayCoercion:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
