default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root

development:
  <<: *default
  database: tmp_development

test:
  <<: *default
  database: tmp_test

production:
  <<: *default
  database: tmp_production
  username: tmp
  password: <%= ENV["TMP_DATABASE_PASSWORD"] %>
