name: PR Checker

on:
  pull_request:
    branches: main

jobs:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true

    - name: Install Ruby Gems
      run: bundle install --jobs 2 --retry 3

    - name: Set up PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 8.15

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.8.0
        cache: 'pnpm'

    - name: Install PNPM dependencies
      run: pnpm install --network-concurrency 2 --fetch-retries 3

    - name: Run Lefthook pre-commit checks
      run: bundle exec lefthook run pre-commit
